version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: 'geneid-server'
    restart: always
    environment: 
      - APP_NAME=GeneId
    expose:
      - "8080"
    volumes:
      - ./server:/server
      - ./tmp:/tmp
    env_file: 
      - .env

  nginx:
    build: ./client
    container_name: 'geneid-nginx'
    restart: always
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
      - ./tmp:/tmp
    ports:
        - "80:80"
    environment:
        - API_HOST=server
        - API_PORT=8080

        
  mongodb:
    image: mongo:latest
    container_name: "geneid-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /var/lib/mongodb-data
      MONDODB_LOG_DIR: /dev/null
    volumes:
     - mongodb-data:/var/lib/mongodb-data
    ports:
      - "27017:27017"

volumes:
  app:
  mongodb-data:
  node_modules:
